### ISSUE TITLE
Publish "official" grafana dashboard on grafana.com

### ISSUE THREAD

**Issue by mcanevet** [saphoooo/freebox_exporter#11]
Nice work!
Would it be possible to share a "official" Grafana dashboard on grafana.com so that we don't have to reinvent the wheel?

**Comment by saphoooo** [comment]
Indeed, could be an interesting side project.

**Comment by mcanevet** [comment]
I created this. https://gist.github.com/mcanevet/863c43f931a3e784f7b985ce14a2f58f
I could publish this on grafana.com, but I think it's a better idea if the dashboard is managed in this project, so that it's updated in case you want to change the metrics name.
What do you think about putting this in a `contrib` folder for a start?

**Comment by saphoooo** [comment]
I agree. Contrib folder is live.
