### ISSUE TITLE
Multiarch images on Docker Hub

### ISSUE THREAD

**Issue by mcanevet** [saphoooo/freebox_exporter#15]
It would be nice to have images on DockerHub available for other arch than amd64.
I did a test using this guide : https://billglover.me/2018/10/30/multi-architecture-docker-builds/ and it's quite easy to do it manually. Here is the result : https://cloud.docker.com/repository/docker/mcanevet/freebox-exporter (see how the latest tag is available for both amd64 and arm64).
The question is how to automate it... I'm not sure this is possible with automatic build...

**Comment by saphoooo** [comment]
I promise to have a look to this as soon as I can, it's already on my TODO list.

**Comment by saphoooo** [comment]
I fix the problem by creating an armv7 build, hope it fits with nyour expectations.

**Comment by mcanevet** [comment]
I'm not sure arm64 is the same than armv7...
FYI, I'm running it on Debian arm64 on Raspberry Pi 3b+ (https://wiki.debian.org/RaspberryPi3)

**Comment by saphoooo** [comment]
RPi A -> armv6
RPi B -> armv7
Both are 32bits

**Comment by mcanevet** [comment]
According to https://en.wikipedia.org/wiki/Raspberry_Pi, "The Raspberry Pi 3+ uses a Broadcom BCM2837B0 SoC with a 1.4 GHz 64-bit quad-core ARM Cortex-A53 processor" and it's ARMv8-A (64/32-bit).

**Comment by saphoooo** [comment]
It's not a problem to build a 64bits image, but it does not make much sense, knowing that all Raspberry 3 are 32bits and that there would be no performance gain.

**Comment by mcanevet** [comment]
Hmmm... Am I misunderstanding something? The Raspberry Pi 3b+ does not have a 64-bit processor?

**Comment by saphoooo** [comment]
Yes indeed, but it's ok to run a 32bits apps. But if you rather prefer an image in 64bits, I can do it.

**Comment by mcanevet** [comment]
I'm not sure docker pull will automatically pull the proper architecture image if I run "docker pull saphoooo/freebox-exporter:latest" from my raspberry. I'll try to find some time to test tonight.

**Comment by saphoooo** [comment]
No, it'll not. I read the doc you pointed me, but I'm not sure to have proper tools (CI) to do it automatically. So, I used a KISS method: two dockerfiles, one for x86_64, and another one for armv7. Use the right tag for your Pi: saphoooo/freebox-exporter:armv7.
