### ISSUE TITLE
Support Lets Encrypt certs in docker

### ISSUE THREAD

**Issue by logut** [saphoooo/freebox_exporter#17]
Bonjour,

En utilisant la version Docker, le certificat https de ma freebox n'est pas reconnu. C'est la freebox qui a demandé automatiquement le certificat chez Lets Encrypt.
```
docker run --name freebox-exporter -p 10001:10001 \
  -e HOME=token -v /home/logut/freebox-export-token:/token saphoooo/freebox-exporter -endpoint "https://xxxx.freeboxos.fr"
2019/07/25 05:58:00 Get https://xxxx.freeboxos.fr/api/v6/login/: x509: certificate signed by unknown authority
```
En utilisant la version binary directement sur mon système (récupérée avec go get) le certificat est reconnu.
```
freebox_exporter -endpoint "https://xxxx.freeboxos.fr"
successfully authenticated
```

Pouvez-vous m'aider ?

**Comment by saphoooo** [comment]
Je pense que c'est parce que c'est un rootless conteneur. Je vais créer une image avec Alpine et les ca-certificates.

**Comment by saphoooo** [comment]
Un retour ?

**Comment by logut** [comment]
Le conteneur se connecte et reconnais le certificat, parfait merci ! :)
