### ISSUE TITLE
VPN rate

### ISSUE THREAD

**Issue by itwars** [saphoooo/freebox_exporter#27]
Bonjour,

J'aime bien la métrique vpn, mais elle est toujours égale à 0 ?

Cdt,
Vincent

**Comment by saphoooo** [comment]
Salut Vincent,

En effet, mais ça ne semble pas venir de l'exporter. net_vpn est documenté dans l'API, par contre, je n'ai pas trouvé de métriques dans la Freebox elle-même. Je vais approfondir.

**Comment by saphoooo** [comment]
Salut Vincent, désolé, je n'ai pas encore eu l'occasion de faire les tests nécessaires (la dernière fois je n'ai pas réussi à me connecter à mon vpn avec mon partage de connexion, et sans ça je ne peux pas investiguer). Mais je ne perds pas cette issue de vue.

**Comment by YannD-Deltagon** [comment]
Hello, j'ai le même problème, mais je pense qu'il est lié a mon erreur "NET"

**Comment by saphoooo** [comment]
J'ai pu faire un test, et en effet, la valeur reste a 0. Cependant, c'est la bonne valeur qui est récupérée en fonction de la documentation (et il faut préciser de RRD est en non stable).
Par ailleurs, impossible de trouver où cette valeur est remontée dans l'interface de la Freebox elle-même. J'ai bien un status du nombre de personnes connectées, mais aucune métriques quant au débit.
Si quelqu'un met la main sur une documentation détaillée, je serais content de l'avoir ; mais en l'absence de celle-ci, je ferme l'issue en considérant que c'est la Freebox elle-même qui ne fournit pas les données, et non un problème au niveau de l'exporter.

**Comment by YannD-Deltagon** [comment]
![image](https://user-images.githubusercontent.com/70691658/95000277-b811d180-05bf-11eb-8306-a1bb0be7d1ed.png)
Désolé, je n'ai pas de doc, mais voila ou je trouve les o/s sur l'interface free, si cela peut aider ;)

**Comment by saphoooo** [comment]
Malheureusement non, je vais encore fouiller la doc, mais je ne suis pas sûr que ça soit remonté via RRD.

**Comment by saphoooo** [comment]
Je vais essayé d'intégré ceci prochainement : [https://dev.freebox.fr/sdk/os/vpn/](https://dev.freebox.fr/sdk/os/vpn/). Pour le moment ce n'est pas comme ça que c'est fait. Par ailleurs, c'est unstable, donc je ne garanti rien.

**Comment by saphoooo** [comment]
tx_bytes and rx_bytes are now available in metrics, but not through RRD.
