### ISSUE TITLE
Freebox in Bridge mode

### ISSUE THREAD

**Issue by tbouquet** [saphoooo/freebox_exporter#28]
Hi,

First of all, thanks for your amazing work, everything seem to work fine

The only thing I can tell is seeing this in my docker logs

`019/12/17 22:45:57 An error occured with LAN metrics: LAN: The API returns an unknown error_code: nodev
2019/12/17 22:46:07 An error occured with LAN metrics: LAN: The API returns an unknown error_code: nodev
2019/12/17 22:46:17 An error occured with LAN metrics: LAN: The API returns an unknown error_code: nodev `

I suppose that is because I use my FB in bridge mode

This is not a real issue, but maybe you'll be able to catch this way of use and prevent this kind of error in the logs

Thanks buddy again for your work

Thomas B.

**Comment by saphoooo** [comment]
The documentation is not very precise and poorly documents the error encountered: https://dev.freebox.fr/sdk/os/lan/. The fix will simply change from unknown error_code to Invalid interface.

Thank you for the feedback, I always appreciate.
