### ISSUE TITLE
Binary or compile procedure ?

### ISSUE THREAD

**Issue by tcaminade** [saphoooo/freebox_exporter#30]
Salut,
Serait-il possible de mettre le bin freebox_exporter ? ou à minima la procédure pour le build please ?

**Comment by saphoooo** [comment]
Salut,
J'ai fait les 2 : j'ai ajouté les binaires pour MacOS, Windows et Linux, ils sont disponibles dans les _**releases**_. J'ai aussi mis à jour le _readme_ afin de pointer sur le gist très complet de **asukakenji** qui explique comment compiler un code go pour tous les OS et toutes les architectures.
