### ISSUE TITLE
Expose more metrics? (All metrics?)

### ISSUE THREAD

**Issue by C-Duv** [saphoooo/freebox_exporter#37]
Issue type: Feature request

I would like to measure more metrics about system, DSL and bandwith usage:
* uptime (`boottime` in node_exporter)
* link, Internet and phone status ("connected" or "disconnected")
* DSL protocol (ADSL, VDSL, etc.)
* last sync DSL timestamp
* cumulative network traffic counter (`node_network_receive_bytes` and `node_network_transmit_bytes` in node_exporter)
* The whole "Stats xDSL" tab of Freebox OS's "État de la Freebox" app.
* Hard disk infos? (disk name, total space, used space)

Are you open to PR for theses metrics (disclaimer: I didn't checked if they were available via Freebox's API but I guess so because someapps have them...)

I've found this other exporter: [trazfr/freebox-exporter](https://github.com/trazfr/freebox-exporter) which seems abandoned but exposed more metrics (by looking at [its `get_metrics.go` source file](ttps://github.com/trazfr/freebox-exporter/blob/master/fbx/get_metrics.go)).

(PS: Of course, thank you for this exporter)

**Comment by saphoooo** [comment]
Of course I'm open for PR, so don't hesitate!
