### ISSUE TITLE
Error when requisition Freeplugs

### ISSUE THREAD

**Issue by SkYNewZ** [saphoooo/freebox_exporter#55]
I got an `auth_required` error when requesting Freeplugs and members is missing a field

```
2021/11/23 23:31:24 An error occured with freeplug metrics: json: cannot unmarshal object into Go struct field freeplug.result of type []main.freeplugNetwork
```

**Comment by droidrider** [comment]
Hi,

I got the same problem with my freebox pop :

2022/03/12 18:56:51 An error occured with freeplug metrics: json: cannot unmarshal object into Go struct field freeplug.result of type []main.freeplugNetwork

box_model_name : Freebox v8 (r1)
api_version : 8.5

I don't use freeplug.

Thank you
